---
- name: Demo on ios_config
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Demo on save_when
      cisco.ios.ios_config:
        lines:
          - ip ssh version 2
        #parents:
        #  - interface Ethernet0/3
        save_when: changed

      register: output

    - name: Display output
      ansible.builtin.debug:
        msg:
         - "{{ output }}"
