---
- name: Demo on resource hostname
  hosts: R1
  gather_facts: false
  tasks:
    - name: Configure hostname
      cisco.ios.ios_hostname:
        config:
          hostname: R1-rendered
        state: merged
      register: output

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"
