---
- name: Demo on to_json and to_nice_json Filters
  hosts: R1
  gather_facts: false
  vars:
    router_details:
      ansible_host: 192.168.29.201
      dns_server: 4.2.2.2
      interface_details:
        - name: GigabitEthernet2
          description: Connected to C8K1
          ip_address: 20.20.20.1
          mask: 255.255.255.0
        - name: GigabitEthernet3
          description: Connected to CSR1
          ip_address: 10.10.10.1
          mask: 255.255.255.0
        - name: GigabitEthernet4
          description: Connected to Core Switch - Faulty Interface
          ip_address: 10.10.20.1
          mask: 255.255.255.0
      device_role: router
  tasks:
    - name: Convert variable to JSON format
      ansible.builtin.debug:
        msg:
          - "{{ router_details }}"
          - "{{ router_details | to_json(indent=4) }}"
