---
- name: Demo on Jinja2 template - for loop and if elif statement
  hosts: R1
  gather_facts: false
  tasks:
    - name: Generate Switchport Configuration
      ansible.builtin.template:
        src: interface_config.j2
        dest: "{{ playbook_dir }}/config_files/{{ inventory_hostname }}_interface_config.cfg"
