all:
  children:
    cisco:
      children:
        ciscoIOS:
          hosts:
            R1:
              ansible_host: 192.168.174.10
              ansible_network_os: cisco.ios.ios
            R2:
              ansible_host: 192.168.174.20
              ansible_network_os: cisco.ios.ios
            R3:
              ansible_host: 192.168.174.30
              ansible_network_os: cisco.ios.ios
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_become: true
    ansible_become_method: enable
    ansible_user: admin
    ansible_password: cisco123
    ntp_server: 1.1.1.1
    dns_server: 8.8.8.8
